COMMON:
    RUN_NAME: CHB106
    OUT_DIR: "/home/gus/MEGAsync/zim/main/BCH/Projects/IBD_portal/data_preprocessing/pipeline_output"
    SHARED:
        REFERENCE_FASTA_PATH:  /run/media/gus/Storage/BCH/data/g1k/reference_genome/human_g1k_v37.fasta


# --------------------------------------
CREATE_SEQ_FAI:
    IN: None
    OUT: None
    PARAMS: None

# --------------------------------------
CREATE_SEQ_DICT:
    IN: None
    OUT: None
    PARAMS: None

# --------------------------------------
VALIDATE_INPUT_VCFS:
    IN:
        VCF_DIR: /home/gus/MEGAsync/zim/main/BCH/Projects/IBD_portal/data_preprocessing/test_fams/VCFs
    OUT: None
    PARAMS: None
